version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "3001:80"
    volumes:
      - .:/app
      - /app/node_modules   # prevents conflict with host node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true   # improves file watching on Mac/WSL
